name: Deploy Vehicle App Project

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.AUTOMATION_PATH }}
            git pull origin main
            docker compose down
            docker rmi backend-test-vehicle_app_project:latest
            docker rmi backend-test-vehicle_db_migration:latest
            docker compose up -d --build